version: "3"
services:
  ubuntu1:
    # replace username/repo:tag with your name and image details
    image: ubuntu:16.04
    deploy:
      placement:
        constraints: [node.role == worker]    
    ports:
      - "8080:8080"
    networks:
      - webnet
  
  ubuntu2:
    image: ubuntu:16.04
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    
    networks:
      - webnet
networks:
  webnet:
    external:
      name: webnet

